### ISSUE TITLE
想问下作者，如何实现私钥加密，公钥解密的接口

### ISSUE THREAD

**Issue by DeforeChen** [cocoajin/Security-iOS#1]
我试了一下，仅仅将两个密钥对调是不可以的。作者有什么方法吗？

**Comment by cocoajin** [comment]
你可以研究下openssl 吧，用那个库；

一般数据签名，用私钥； 验证签名用公钥

**Comment by cocoajin** [comment]
私钥加密，用公钥密钥，还有什么意义，公钥大家都知道了
